### ISSUE TITLE
return statement copy elision error from clang

### ISSUE THREAD

**Issue by apanqasem** [NUCAR-DEV/Hetero-Mark#55]
Trying to build with clang 4.0.0. Getting the following error when trying to build command_line_option.cc. Is this a known problem? Any suggestions for a workaround? 

```
/home/apan/hetereomark/src/common/command_line_option/argument_value_factory.h:51:12: error: moving a
      local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
    return std::move(argument_value);
           ^
/home/apan/hetereomark/src/common/command_line_option/argument_value_factory.h:51:12: note: remove
      std::move call here
    return std::move(argument_value);
```

**Comment by syifan** [comment]
This problem is solved in most recent version of the Develop branch.
